"""add country column to agents

Revision ID: 68c6ff8580b2
Revises: 6c671c1b922d
Create Date: 2026-05-14 16:20:01.069719
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68c6ff8580b2'
down_revision: str | None = '6c671c1b922d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Inside apps/api/alembic/versions/68c6ff8580b2_...py

def upgrade() -> None:
    # Change this line:
    # op.add_column('agents', sa.Column('country', sa.String(length=255), nullable=False))

    # To this (adding server_default):
    op.add_column(
        'agents',
        sa.Column(
            'country',
            sa.String(length=255),
            nullable=False,
            server_default='Morocco'  # <── ADD THIS
        )
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'country')
    # ### end Alembic commands ###
