"""add agent and channel registration tables

Revision ID: 6c671c1b922d
Revises: 7cb5ac062976
Create Date: 2026-05-14 13:55:39.386651
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6c671c1b922d"
down_revision: str | None = "7cb5ac062976"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("phone", sa.String(length=50), nullable=True),
        sa.Column("company", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_agents_city", "agents", ["city"], unique=False)
    op.create_index("ix_agents_email", "agents", ["email"], unique=False)
    op.create_table(
        "channel_registrations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_id", sa.UUID(), nullable=True),
        sa.Column("channel_url", sa.String(length=2048), nullable=False),
        sa.Column("channel_name", sa.String(length=500), nullable=True),
        sa.Column("channel_id", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "APPROVED", "REJECTED", "DISABLED", name="channelstatus"),
            nullable=False,
        ),
        sa.Column("max_videos", sa.Integer(), nullable=False),
        sa.Column("rejection_reason", sa.Text(), nullable=True),
        sa.Column(
            "discovered_via",
            sa.String(length=50),
            nullable=True,
            comment="manual | admin_search | agent_registration",
        ),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["agent_id"], ["agents.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_channel_registrations_channel_url",
        "channel_registrations",
        ["channel_url"],
        unique=False,
    )
    op.create_index(
        "ix_channel_registrations_region", "channel_registrations", ["region"], unique=False
    )
    op.create_index(
        "ix_channel_registrations_status", "channel_registrations", ["status"], unique=False
    )
    op.create_index(
        "ix_locations_geom", "locations", ["geom"], unique=False, postgresql_using="gist"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_locations_geom", table_name="locations", postgresql_using="gist")
    op.drop_index("ix_channel_registrations_status", table_name="channel_registrations")
    op.drop_index("ix_channel_registrations_region", table_name="channel_registrations")
    op.drop_index("ix_channel_registrations_channel_url", table_name="channel_registrations")
    op.drop_table("channel_registrations")
    op.drop_index("ix_agents_email", table_name="agents")
    op.drop_index("ix_agents_city", table_name="agents")
    op.drop_table("agents")
    # ### end Alembic commands ###
