"""initial schema fixed

Revision ID: 7cb5ac062976
Revises:
Create Date: 2026-05-11 20:48:09.937630
"""

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cb5ac062976"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "video_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column(
            "platform", sa.Enum("YOUTUBE", "TIKTOK", "INSTAGRAM", name="platform"), nullable=False
        ),
        sa.Column(
            "external_id",
            sa.String(length=255),
            nullable=False,
            comment="Platform-specific video ID",
        ),
        sa.Column("channel_id", sa.String(length=255), nullable=True),
        sa.Column("channel_name", sa.String(length=500), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=True),
        sa.Column("raw_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_index("ix_video_sources_channel_id", "video_sources", ["channel_id"], unique=False)
    op.create_index("ix_video_sources_external_id", "video_sources", ["external_id"], unique=False)
    op.create_index("ix_video_sources_platform", "video_sources", ["platform"], unique=False)
    op.create_index(
        "ix_video_sources_published_at", "video_sources", ["published_at"], unique=False
    )
    op.create_table(
        "processing_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_source_id", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "INGESTING",
                "TRANSCRIBING",
                "EXTRACTING",
                "GEOCODING",
                "COMPLETED",
                "FAILED",
                "SKIPPED",
                name="processingstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "current_stage",
            sa.String(length=50),
            nullable=True,
            comment="Current pipeline stage name",
        ),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stage", sa.String(length=50), nullable=True),
        sa.Column("error_traceback", sa.Text(), nullable=True),
        sa.Column(
            "stage_timings",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Timing per stage: {ingestion: 12.3, transcription: 45.6, ...}",
        ),
        sa.Column(
            "stage_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Per-stage metadata: {transcription: {wer: 0.15}, extraction: {tokens_used: 1200}}",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_source_id"], ["video_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_source_id"),
    )
    op.create_index(
        "ix_processing_jobs_created_at", "processing_jobs", ["created_at"], unique=False
    )
    op.create_index("ix_processing_jobs_status", "processing_jobs", ["status"], unique=False)
    op.create_table(
        "properties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_source_id", sa.UUID(), nullable=False),
        sa.Column(
            "property_type",
            sa.Enum(
                "APARTMENT",
                "HOUSE",
                "VILLA",
                "LAND",
                "COMMERCIAL",
                "GARAGE",
                "OTHER",
                name="propertytype",
            ),
            nullable=False,
        ),
        sa.Column(
            "listing_type", sa.Enum("SALE", "RENT", "UNKNOWN", name="listingtype"), nullable=False
        ),
        sa.Column("price", sa.Float(), nullable=True, comment="Price in MAD"),
        sa.Column("price_currency", sa.String(length=3), nullable=False),
        sa.Column(
            "price_raw",
            sa.String(length=255),
            nullable=True,
            comment="Original price text from video",
        ),
        sa.Column("area_sqm", sa.Float(), nullable=True, comment="Area in square meters"),
        sa.Column("rooms", sa.Integer(), nullable=True),
        sa.Column("bedrooms", sa.Integer(), nullable=True),
        sa.Column("bathrooms", sa.Integer(), nullable=True),
        sa.Column("floors", sa.Integer(), nullable=True),
        sa.Column("has_garage", sa.Boolean(), nullable=True),
        sa.Column("has_garden", sa.Boolean(), nullable=True),
        sa.Column("has_elevator", sa.Boolean(), nullable=True),
        sa.Column(
            "floor_number", sa.Integer(), nullable=True, comment="Which floor (for apartments)"
        ),
        sa.Column(
            "legal_status",
            sa.Enum("MELKIA", "TABOU", "RASM", "UNKNOWN", name="legalstatus"),
            nullable=False,
        ),
        sa.Column(
            "title_generated", sa.String(length=500), nullable=True, comment="LLM-generated title"
        ),
        sa.Column(
            "description_generated", sa.Text(), nullable=True, comment="LLM-generated description"
        ),
        sa.Column(
            "extraction_confidence",
            sa.Float(),
            nullable=True,
            comment="Overall extraction confidence 0-1",
        ),
        sa.Column(
            "field_confidences",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Per-field confidence: {price: 0.95, area: 0.8, ...}",
        ),
        sa.Column(
            "video_timestamp_start",
            sa.Float(),
            nullable=True,
            comment="Where in the video this property tour starts (seconds)",
        ),
        sa.Column("video_timestamp_end", sa.Float(), nullable=True),
        sa.Column(
            "prompt_version",
            sa.String(length=50),
            nullable=True,
            comment="Which prompt version extracted this data",
        ),
        sa.Column(
            "extras",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Flexible field for additional extracted data",
        ),
        sa.Column("is_published", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column(
            "needs_review",
            sa.Boolean(),
            nullable=False,
            comment="Flagged for human review (low confidence)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_source_id"], ["video_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_properties_area", "properties", ["area_sqm"], unique=False)
    op.create_index("ix_properties_created_at", "properties", ["created_at"], unique=False)
    op.create_index("ix_properties_listing_type", "properties", ["listing_type"], unique=False)
    op.create_index("ix_properties_needs_review", "properties", ["needs_review"], unique=False)
    op.create_index("ix_properties_price", "properties", ["price"], unique=False)
    op.create_index("ix_properties_published", "properties", ["is_published"], unique=False)
    op.create_index("ix_properties_type", "properties", ["property_type"], unique=False)
    op.create_table(
        "transcripts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_source_id", sa.UUID(), nullable=False),
        sa.Column("full_text", sa.Text(), nullable=False),
        sa.Column(
            "language",
            sa.String(length=10),
            nullable=False,
            comment="Detected language code (ar, fr, etc.)",
        ),
        sa.Column(
            "confidence", sa.Float(), nullable=True, comment="Overall transcription confidence 0-1"
        ),
        sa.Column(
            "segments",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Timestamped segments: [{start, end, text, confidence}]",
        ),
        sa.Column(
            "whisper_model",
            sa.String(length=50),
            nullable=True,
            comment="Whisper model version used",
        ),
        sa.Column("processing_time_seconds", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["video_source_id"], ["video_sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("video_source_id"),
    )
    op.create_index("ix_transcripts_language", "transcripts", ["language"], unique=False)
    op.create_table(
        "locations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("property_id", sa.UUID(), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
            comment="PostGIS point geometry for spatial queries",
        ),
        sa.Column(
            "address_raw", sa.Text(), nullable=True, comment="Original location text from video"
        ),
        sa.Column("address_formatted", sa.Text(), nullable=True),
        sa.Column("neighborhood", sa.String(length=255), nullable=True),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("region", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column(
            "geocoding_provider",
            sa.String(length=50),
            nullable=True,
            comment="nominatim | google | local_gazetteer",
        ),
        sa.Column("geocoding_confidence", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["property_id"], ["properties.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("property_id"),
    )
    op.create_index(
        "idx_locations_geom", "locations", ["geom"], unique=False, postgresql_using="gist"
    )
    op.create_index("ix_locations_city", "locations", ["city"], unique=False)
    op.create_index("ix_locations_neighborhood", "locations", ["neighborhood"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_locations_neighborhood", table_name="locations")
    op.drop_index("ix_locations_city", table_name="locations")
    op.drop_index("idx_locations_geom", table_name="locations", postgresql_using="gist")
    op.drop_table("locations")
    op.drop_index("ix_transcripts_language", table_name="transcripts")
    op.drop_table("transcripts")
    op.drop_index("ix_properties_type", table_name="properties")
    op.drop_index("ix_properties_published", table_name="properties")
    op.drop_index("ix_properties_price", table_name="properties")
    op.drop_index("ix_properties_needs_review", table_name="properties")
    op.drop_index("ix_properties_listing_type", table_name="properties")
    op.drop_index("ix_properties_created_at", table_name="properties")
    op.drop_index("ix_properties_area", table_name="properties")
    op.drop_table("properties")
    op.drop_index("ix_processing_jobs_status", table_name="processing_jobs")
    op.drop_index("ix_processing_jobs_created_at", table_name="processing_jobs")
    op.drop_table("processing_jobs")
    op.drop_index("ix_video_sources_published_at", table_name="video_sources")
    op.drop_index("ix_video_sources_platform", table_name="video_sources")
    op.drop_index("ix_video_sources_external_id", table_name="video_sources")
    op.drop_index("ix_video_sources_channel_id", table_name="video_sources")
    op.drop_table("video_sources")
    # ### end Alembic commands ###
